-- Create trips table
CREATE TABLE IF NOT EXISTS trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  user_name TEXT NOT NULL,
  vehicle_type TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed'))
);

-- Create requests table
CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  trip_id BIGINT REFERENCES trips(id) ON DELETE CASCADE,
  passenger_name TEXT NOT NULL,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected'))
);

-- Enable Realtime for these tables
ALTER PUBLICATION supabase_realtime ADD TABLE trips;
ALTER PUBLICATION supabase_realtime ADD TABLE requests;

-- Policy (Allowing public access for simplicity in development, BUT IN PRODUCTION RESTRICT THIS)
ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read" ON trips FOR SELECT USING (true);
CREATE POLICY "Public Insert" ON trips FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update" ON trips FOR UPDATE USING (true);

ALTER TABLE requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read" ON requests FOR SELECT USING (true);
CREATE POLICY "Public Insert" ON requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update" ON requests FOR UPDATE USING (true);

-- Custom users table for pure username/password auth
CREATE TABLE IF NOT EXISTS app_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

-- Policy for app_users
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Full Access" ON app_users FOR ALL USING (true) WITH CHECK (true);
